services:
    db:
        image: postgres:16
        restart: on-failure
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=main
            - POSTGRES_DB=application
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - app
    api:
        build: 
            context: ./backend/
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - app
        container_name: api-ride

networks:
    app:
        driver: bridge