FROM node:22.11.0-alpine

WORKDIR /tmp/react

COPY frontend/package.json  .
COPY .env .
COPY frontend/ .

RUN npm install

RUN npm run build

RUN mkdir -p /var/www/html
RUN mv .env /var/www/html
RUN mv dist/* /var/www/html
VOLUME /var/www/html

WORKDIR /


RUN rm -rf /tmp/react
